[programs.devnet]
myepicproject = "3X77VHYBQQm2KJNEpYxZ8QLLHjB7odFBHgRhWsMVHDyk"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/dhruv/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js" 
